In [1]:
import pandas as pd

df = pd.DataFrame({
    "Gender": ["M","F","M","F"],
    "Region": ["North","North","South","South"],
    "Sales": [100,200,150,300]
})

In [2]:
df.pivot_table(
    values="Sales",
    index="Gender",
    aggfunc="sum"
)

        Sales
Gender
F         500
M         250

In [3]:
df.pivot_table(
    values="Sales",
    index="Gender",
    columns="Region",
    aggfunc="sum"
)

Region  North  South
Gender
F         200    300
M         100    150

In [1]:
# Necessary libraries for plotting
from plotnine import * ## needed to 
import seaborn as sns  
import matplotlib.pyplot as plt 

# libraries for data importation and manipulation
import numpy as np  
import pandas as pd  

## libraries for dimensionality reduction
from sklearn import decomposition ## needed module to perform PCA
from sklearn.preprocessing import StandardScaler ## needed to 
import torch ## needed to 
import torch.nn as nn ## needed to 
from torchvision import transforms # needed for data processing

# libraries for clustering
from sklearn.cluster import AgglomerativeClustering ## needed to 
from scipy.cluster.hierarchy import dendrogram, linkage ## needed to perform and display the dendrogram
from sklearn.metrics import silhouette_samples, silhouette_score ## needed for clusters's evaluation
from scipy.spatial.distance import pdist, squareform ## needed to perform distance metric
from sklearn.cluster import KMeans ## needed to perform KMeans clustering
from sklearn_extra.cluster import KMedoids ## needed to perform other metrics except euclidian distance 


# Libraries for linear and logistic regressions 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_squared_error

In [2]:
bcg = pd.read_excel("DatoWorks/Virtual internships/Campaign_Data_Week1.xlsx",sheet_name="Raw_Data")

FileNotFoundError: [Errno 2] No such file or directory: 'DatoWorks/Virtual internships/Campaign_Data_Week1.xlsx'